server:
  port: 5000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: test-topic
    listener:
      concurrency: 5
    consumer:
      group-id: test-group
      client-id: 200
      max-poll-records: 200
      auto-offset-reset: earliest
    producer:
      batch-size: 1000
      retries: 3
      client-id: 200
zuul:
  routes:
    service_1:
      path: /service_1/**
    service_2:
      path: /service_2/**

